#!/usr/bin/env python3
"""Emit the scoring rules the leaderboard worker needs, from the Python originals.

The worker recalculates every score it is sent rather than trusting the number the
browser reports - that is the whole reason the leaderboard is worth reading. But a
recalculation is only useful if it matches the game: if the worker and the game drift
apart, honest players get marked down for scores they really did earn.

So the constants are written once, in backend/app/game.py, and copied from there into
a file the worker imports. tests/test_worker_rules.py regenerates this file and fails
if it differs from what is checked in, which turns drift into a red test rather than
a slow leak of wrong scores.

Quick Fire works the same way, except that its constants start life as data in
data/quiz_rules.json rather than as Python. The sizes of the quiz packs are
folded in here too, so the worker can tell a possible score from an impossible one.

    python scripts/generate_worker_rules.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from backend.app.game import (  # noqa: E402
    CLUE_COSTS,
    COMPLETION_BONUS,
    DIFFICULTIES,
    POINTS_PER_PLAYER,
    POINTS_PER_SECOND_REMAINING,
)

OUTPUT = REPO_ROOT / "worker" / "src" / "rules.generated.json"
QUIZ_OUTPUT = REPO_ROOT / "worker" / "src" / "quiz-rules.generated.json"
QUIZ_RULES = REPO_ROOT / "data" / "quiz_rules.json"
QUIZ_PACKS = REPO_ROOT / "data" / "quizzes"


def rules() -> dict:
    return {
        "_comment": "Generated by scripts/generate_worker_rules.py - do not edit by hand.",
        "pointsPerPlayer": POINTS_PER_PLAYER,
        "completionBonus": COMPLETION_BONUS,
        "pointsPerSecondRemaining": POINTS_PER_SECOND_REMAINING,
        "clueCosts": dict(CLUE_COSTS),
        "difficulties": {
            key: {"seconds": d.seconds, "multiplier": d.multiplier, "freebies": d.freebies}
            for key, d in DIFFICULTIES.items()
        },
    }


def quiz_rules() -> dict:
    """The quiz's rules, plus the size of every pack.

    The sizes are what let the worker call a score impossible. Without them a round
    claiming twenty right answers out of a twelve question pack has nothing to be
    checked against, and the board is only as honest as the browser that posted to it.
    """
    source = json.loads(QUIZ_RULES.read_text(encoding="utf-8"))
    out = {key: value for key, value in source.items() if not key.startswith("_")}
    out["_comment"] = "Generated by scripts/generate_worker_rules.py - do not edit by hand."
    out["packs"] = {
        pack["id"]: len(pack["questions"])
        for pack in (
            json.loads(path.read_text(encoding="utf-8"))
            for path in sorted(QUIZ_PACKS.glob("*.json"))
        )
    }
    return out


def render() -> str:
    return json.dumps(rules(), indent=2, sort_keys=True) + "\n"


def render_quiz() -> str:
    return json.dumps(quiz_rules(), indent=2, sort_keys=True) + "\n"


def main() -> int:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(render(), encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(REPO_ROOT)}")
    QUIZ_OUTPUT.write_text(render_quiz(), encoding="utf-8")
    print(f"Wrote {QUIZ_OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
